# Generated by Django 4.2.7 on 2023-11-20 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=100)),
                ('emp_dept', models.CharField(max_length=100)),
                ('emp_company', models.CharField(max_length=100)),
            ],
        ),
    ]
