# Generated by Django 4.2.7 on 2023-11-24 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='fooditem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('price', models.IntegerField(max_length=10)),
                ('rating', models.FloatField(max_length=5)),
                ('image', models.ImageField(upload_to='img')),
            ],
        ),
    ]
